name: football-player-framework
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - pyyaml
  - openpyxl
  - tqdm
  - pytest
  - kaggle
  - pytorch
  - pip
  - pip:
      - sentence-transformers>=3.0.0
      - annoy>=1.17.3
