ALTER TABLE "USUARIO" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PESQUISA" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LIGA" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CLUBE" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "JOGADOR" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ESTATISTICA" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_all_usuario" ON "USUARIO"
  FOR ALL TO anon USING (true) WITH CHECK (true);

CREATE POLICY "anon_all_pesquisa" ON "PESQUISA"
  FOR ALL TO anon USING (true) WITH CHECK (true);

CREATE POLICY "anon_all_liga" ON "LIGA"
  FOR ALL TO anon USING (true) WITH CHECK (true);

CREATE POLICY "anon_all_clube" ON "CLUBE"
  FOR ALL TO anon USING (true) WITH CHECK (true);

CREATE POLICY "anon_all_jogador" ON "JOGADOR"
  FOR ALL TO anon USING (true) WITH CHECK (true);

CREATE POLICY "anon_all_estatistica" ON "ESTATISTICA"
  FOR ALL TO anon USING (true) WITH CHECK (true);
