model:
  model_name: "BM25Model"
  name: "BM25Model"
  parameters:
    index_name: "bm25_player_index"
    model: "bm25"
    query_col: "search_query"
    doc_col: "document"
    doc_id_col: "document_id"
    hyperparams:
      b: 0.75
      k1: 1.5
